### ISSUE TITLE
CNSU 2022

### ISSUE THREAD

**Issue by Helias** [UNICT-DMI/UNICT-Elezioni#128]
https://www.unict.it/sites/default/files/files/Scrutinio%20CNSU%20provvisorio.pdf

making some tries I get this
```
Traceback (most recent call last):
  File "/Users/4009093/projects/UNICT-elezioni/jsonParser/parser.py", line 87, in <module>
    main(sys.argv[1:])
  File "/Users/4009093/projects/UNICT-elezioni/jsonParser/parser.py", line 74, in main
    str_json = target.scrape_list(formatted_text)
  File "/Users/4009093/projects/UNICT-elezioni/jsonParser/CNSU.py", line 160, in scrape_list
    list_of_seats = self.__find_list_of_seats(text, list_of_not, seggi_da_assegnare)
  File "/Users/4009093/projects/UNICT-elezioni/jsonParser/CNSU.py", line 19, in __find_list_of_seats
    seggi_da_assegnare[0] = int(split_text[2])
IndexError: list index out of range
```

**Comment by Helias** [comment]
closed by https://github.com/UNICT-DMI/UNICT-Elezioni/pull/150
